#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Email-MIME-Encodings
Version  : 1.316
Release  : 22
URL      : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-MIME-Encodings-1.316.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-MIME-Encodings-1.316.tar.gz
Summary  : 'A unified interface to MIME encoding and decoding'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Email-MIME-Encodings-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
This archive contains the distribution Email-MIME-Encodings,
version 1.316:
A unified interface to MIME encoding and decoding

%package dev
Summary: dev components for the perl-Email-MIME-Encodings package.
Group: Development
Provides: perl-Email-MIME-Encodings-devel = %{version}-%{release}
Requires: perl-Email-MIME-Encodings = %{version}-%{release}

%description dev
dev components for the perl-Email-MIME-Encodings package.


%package perl
Summary: perl components for the perl-Email-MIME-Encodings package.
Group: Default
Requires: perl-Email-MIME-Encodings = %{version}-%{release}

%description perl
perl components for the perl-Email-MIME-Encodings package.


%prep
%setup -q -n Email-MIME-Encodings-1.316
cd %{_builddir}/Email-MIME-Encodings-1.316

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Email::MIME::Encodings.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
